name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main   

env:
    DBT_PROFILES_DIR: ${{ github.workspace }}
    DBT_PROJECT_DIR: ${{ github.workspace }}
    BIGQUERY_DATASET: ci_dbt_bigquery_analytics
    BIGQUERY_PROJECT: indicium-sandbox
    DBT_JOB_TIMEOUT: 300
    DBT_THREADS: 16
    DBT_JOB_RETRIES: 1

jobs:
  dbt-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.BIGQUERY_AUTH }}"

      - name: Run dbt debug 
        run: dbt debug 

      - name: dbt deps
        run: dbt deps

      - name: dbt compile
        run: dbt compile
